### ISSUE TITLE
Weird Add Button in the side navigation bar.

### ISSUE THREAD

**Issue by SoumavaSeal** [SoumavaSeal/BillSplit#9]
The add button in the side navigation bar does not fit properly with the rest of the layout. It needs to be scaled down.

**Comment by SkywalkerSoumya** [comment]
whole layout is updated now...kindly check that.

**Comment by SoumavaSeal** [comment]
The bug is fixed and the layout has been updated. The changes are moved to the master branch by the commit "c733ddf088bac08a455cc5a6a1fa28a6908096ec".
